### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by grosser** [comment]
how did you review this PR in 10s ? :D

**Comment by grosser** [comment]
I'll make a fixup ... need to have a workflow on master to see ci failures

**Comment by gregorym** [comment]
EPIC FAIL :D

**Comment by grosser** [comment]
nah, it does not run CI until the workflow is on master ... so I'd have merged it too :D

**Comment by grosser** [comment]
all good now, you can make a new release

**Pull request merged**
