### PR TITLE
allow me to specify tag

### PR DESCRIPTION
**Pull request by apanzerj**
@grosser I like this better :-D
@gregorym  this could go either way between these two PR's (https://github.com/gregorym/bump/issues/42) and it's really a matter of personal preference but the last two commits on this branch are worth keeping as they fix issues with ree/older ruby versions and the parallel gem.

### CODE REVIEW

**Comment by apanzerj** [comment]
@gregorym thoughts?

**Comment by gregorym** [comment]
Thanks @apanzerj

**Comment by apanzerj** [comment]
Thanks for letting me contribute :-D

**Comment by apanzerj** [comment]
@gregorym can you release the gem?

**Comment by gregorym** [comment]
yes I will take care of it today.

**Comment by apanzerj** [comment]
thanks :-D

**Comment by gregorym** [comment]
Done :)

**Pull request merged**
