### PR TITLE
make travis faster

### PR DESCRIPTION
**Pull request by grosser**
@gregorym only merge on green ... trying to debug the erros here

### CODE REVIEW

**Comment by grosser** [comment]
Yeah all green ! :D

**Comment by grosser** [comment]
ok, time for a new release ? :)

**Comment by gregorym** [comment]
Yep. I just restarted the build on #47 as it was failing.

**Comment by gregorym** [comment]
I mean #46

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I just noticed that Travis `cache:` was enabled by this pull request, whereas [Travis caching feature was available since December 17, 2014](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure) (about a year before). I am interested in understanding the reason behind delaying the `cache` feature in this repository.

Thank you.

**Comment by grosser** [comment]
same as other PRs ... did not know it was supported

**Comment by Taher-Ghaleb** [comment]
Sorry for the interruption again, @grosser, and thank you for your gentle response.

**Pull request merged**
