### PR TITLE
Remove descriptive text from `current` and `file` output

### PR DESCRIPTION
**Pull request by bethesque**
So it can be used more cleanly by command line tools.

### CODE REVIEW

**Review by grosser — APPROVED** [review]
so nice! :D

**Comment by grosser** [comment]
@gregorym you good with this ?
... want to bump this as minor or major ?

**Comment by gregorym** [comment]
I will merge the 2 CR and bump to a minor version EOD.

**Comment by bethesque** [comment]
Thanks :) Now to get my `conventional_changelog` changes merged! The two gems work together beautifully and make automated releases a breeze. Appreciate your work.

**Pull request merged**
